name: CI

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - emacs: 27.1
            lint: false
          - emacs: 29.1
            lint: true
          - emacs: snapshot
            lint: false
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs }}
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: emacs -Q -l .github/workflows/init.el -batch
                    --eval "(package-install 'reformatter)"
                    --eval "(package-install 'package-lint)"

    - name: Compile
      run: emacs -Q -l .github/workflows/init.el -batch
                    -L . -f batch-byte-compile *.el

    - name: Lint
      if: ${{ matrix.lint }}
      run: emacs -Q -l .github/workflows/init.el -batch
                    --eval '(setq package-lint-main-file "uiua-mode.el")'
                    -f package-lint-batch-and-exit *.el
